name: tito_api_wrapper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.92
  - uvicorn
  - requests
  - pip=22
  - omegaconf
  - structlog
  - unidecode
  # TESTING
  - pytest=7
  - pip:
       - starlette_context
