name: tito_api_wrapper_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.92
  - uvicorn
  - requests
  - pip=22
  - omegaconf
  - structlog
  - boto3
  # TESTING
  - pytest=7
  # sphinx: doc generation
  - sphinx-book-theme
  - myst-parser
  - sphinx-autodoc-typehints
  - sphinx-autoapi
  - graphviz
  - linkify-it-py
  - mistune=0.8.4  # newer mistune 2 is a re-write and not tested, yet
  - sphinxcontrib-openapi
  - sphinx=4.5  # working version, 5+ seems not to work
  # TESTING & QUALITY
  - black=22.3.*
  - pre-commit
  - pytest=7
  # VERSIONING
  - bump2version
  - pip:
       - starlette_context

