########################################################################################
########################################################################################
# This is the BASIC configuration, it's always loaded.
# To change the configuration depending on the environment, any params there will
# overwrite settings below.
# Omegaconf replaces all references to e.g. ${default.HOST} with one line/update for
# all nodes using the reference once loaded `default.HOST = "cool.com"`.
########################################################################################
########################################################################################

MODE: null

PROJECT_NAME: Fact Check-In

LOG:
  DIR: ../log/app
  NAME: fact-check-in.log
  TO_FILE: false
  TO_SCREEN: false

# application settings
APP:
  PORT: 9898
  HOST: "127.0.0.1"

include_activities:
  # activities that are relevant for this service
  - on_site
  - online_access

organizer_speakers:
  - "XYZA-1"  # J Doe

