########################################################################################
########################################################################################
# This is the BASIC configuration, it's always loaded.
# To change the configuration depending on the environment, any params there will
# overwrite settings below.
# Omegaconf replaces all references to e.g. ${default.HOST} with one line/update for
# all nodes using the reference once loaded `default.HOST = "cool.com"`.
########################################################################################
########################################################################################

MODE: null

PROJECT_NAME: TITO API WRAPPER

LOG:
  DIR: ../log/app
  NAME: TITO_API.log
  TO_FILE: false
  TO_SCREEN: false

# application settings
APP:
  PORT: 8080
  HOST: "127.0.0.1"


account_slug: pysv
event_slug: pyconde-pydata-berlin-2023


exclude_ticket_patterns:
- childcare
- luggage
- social